### ISSUE TITLE
Package deployment no rpi-3 option 

### ISSUE THREAD

**Issue by theHound9987** [luxas/kubernetes-on-arm#114]
I was trying to use your package deployment option because I only have a mac at home. There was not option to tell your package that my boards are rpi-3. I'm I missing some thing, if not can you please update the package? Thanks

**Comment by luxas** [comment]
You may just use `rpi-2` and it should work well

Hopefully soon, I'll have a new release up

**Comment by theHound9987** [comment]
That worker for me thanks.

**Comment by luxas** [comment]
Closing since v0.8.0 has the rpi-3 option
