### ISSUE TITLE
what happened to v0.8.0

### ISSUE THREAD

**Issue by mitchhh22** [luxas/kubernetes-on-arm#119]
The dev branch gives the download to v0.8.0
`wget https://github.com/luxas/kubernetes-on-arm/releases/download/v0.8.0/docker-multinode.deb`
but the link 404's.. did that release get removed?

**Comment by luxas** [comment]
No, I just started to bump the version numbers :)
I'm going to release it this week.

Thanks for your patiance

**Comment by mitchhh22** [comment]
Awesome, cant wait!

**Comment by luxas** [comment]
Now released! Have fun :)
