### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by jamesbuckett** [luxas/kubernetes-on-arm#122]
When executing `wget https://github.com/luxas/kubernetes-on-arm/releases/download/v0.8.0/kube-systemd.deb`

Error : `HTTP request sent, awaiting response... 404 Not Found`

File not present ?

**Comment by luxas** [comment]
Oops, look at the `.deb` file attached to release.
Copy-paste error in the downloads section, should be `docker-multinode.deb`

Now fixed
