### ISSUE TITLE
rkt + kubernetes on arm

### ISSUE THREAD

**Issue by yanpozka** [luxas/kubernetes-on-arm#130]
I'd love to run kubernetes with [rkt](http://kubernetes.io/docs/getting-started-guides/rkt/), it's possible to run them on top of arms ?

I'm wiling to help with this idea, I'm a Go programmer, but I don't have great bash skills.

**Comment by TimCook1** [comment]
That's more of a question for the rkt crew, but yes they do support ARM:
https://github.com/appc/spec/issues/417

**Comment by luxas** [comment]
In favor for the idea! If you come up with something, report back here!
