### ISSUE TITLE
Scaleway

### ISSUE THREAD

**Issue by faddat** [luxas/kubernetes-on-arm#15]
I feel compelled to get this working on scaleway.  This of course blocks me from using a "flash your sdcard" deploy.  Any thoughts on where I might get started?

Thanks!

**Comment by luxas** [comment]
How do one "flash" things to Scaleway? 
Is there prebuilt Arch Linux ARM or Debian 8?
I think it shouldn't hard to make a `.deb` file of this project, and in that case one may install via something like this:
```
wget https://github.com/luxas/kubernetes-on-arm/releases/v0.6.0/kubernetes.deb
dpkg -i kubernetes.deb
```

**Comment by faddat** [comment]
100 thanks sir :D.
