### ISSUE TITLE
Where is the Prometheus image?

### ISSUE THREAD

**Issue by alexellis** [luxas/kubernetes-on-arm#156]
Hi Luxas - I need to find your Dockerfile for this image so I can rebuild it.

https://hub.docker.com/r/luxas/prometheus-arm64/tags/

Can you help? It doesn't appear to be documented on the Hub repo.

**Comment by luxas** [comment]
It's here: https://github.com/luxas/kubeadm-workshop
Run `make -C images/prometheus` on an amd64 machine, and it will do everything for you
