### ISSUE TITLE
How to create a web session with a pod/service?

### ISSUE THREAD

**Issue by gyoho** [luxas/kubernetes-on-arm#23]
Is there any way to initiate a web session with a running pod/service in order to provide realtime-interactive web service?

**Comment by luxas** [comment]
What do you mean with session? Cookies?
Isn't it default, or how you configure the web app?

**Comment by luxas** [comment]
I don't think this is a k8s-on-arm issue. You'll probably find information how to do this from mainline k8s or the web.

Reopen if it isn't working, and it's a ARM issue
