### ISSUE TITLE
kube-config install checking

### ISSUE THREAD

**Issue by TimCook1** [luxas/kubernetes-on-arm#37]
There should probably be some checking in the kube-config install script.  If you happen to make a typo, rather than tell you that you've picked an invalid option, it just completes then errors out.  Example:

Which OS do you have? Options: [archlinux, hypriotos, systemd]. hypriot
/usr/bin/kube-config: line 103: /etc/kubernetes/dynamic-env/hypriot.sh: No such file or directory

**Comment by luxas** [comment]
Yes, you're right. Thanks for noticing. Will fix to `v0.6.3`

**Comment by luxas** [comment]
This should be fixed in `v0.6.3`. 
Thank you for finding this bug.
Reopen if it doesn't work
