### ISSUE TITLE
kube2sky and skydns won't work

### ISSUE THREAD

**Issue by sokoow** [luxas/kubernetes-on-arm#41]
I got 

{"log":"2016/01/03 10:46:01 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [5]\n","stream":"stderr","time":"2016-01-03T10:46:01.494293735Z"}

and none of hosts would register with DNS, any idea on how to debug it ?

**Comment by sokoow** [comment]
never mind, it worked after creating images again, magic

**Comment by luxas** [comment]
I'm glad it solved!

**Comment by sokoow** [comment]
Any idea how to setup networking for workers so that whole network sees
them ? So far I can only see services within cluster

**Comment by luxas** [comment]
See: https://github.com/luxas/kubernetes-on-arm#access-your-cluster
