### ISSUE TITLE
verify image pull policy

### ISSUE THREAD

**Issue by saturnism** [luxas/kubernetes-on-arm#48]
I noticed that the image pull policy is not set in the static pod yamls. The images pulled also don't have specific tags.  IIRC, this means that Kubernetes may be applying the default pull always policy.

Would it be possible to do either one of the following?
* specify the image pull policy
* tag the docker images and specify the tags in the pod yamls?

**Comment by luxas** [comment]
The images are tagged with e.g. `v0.6.2`. It's just not tagged in the `json` file.

If I get you right, you mean that this could be a problem when newer images (e.g. `v0.6.5`) appear and k8s has `imagePullPolicy: always`, so `v0.6.2` images will be replaced with `v0.6.5` on older clusters.

Is that what you meant?
Seems resonable I could specify an explicit `imagePullPolicy: IfNotPresent` and then the user may pull newer images if he/she want to.

**Comment by saturnism** [comment]
yup! sgtm.

**Comment by luxas** [comment]
Fixed with: 5449eae4c565c4075ae826efbf0598cdf534df86
