### ISSUE TITLE
Hostname for master 

### ISSUE THREAD

**Issue by lavvy** [luxas/kubernetes-on-arm#54]
Hey can the master be connected to by its Hostname.  

For instance :
To enable the worker service, run
kube-config enable-worker [master-ip or hostname]

**Comment by luxas** [comment]
@lavvy I can test if it works on my cluster. Maybe... 
If you can ping your master node by hostname from a worker, it should be possible to use hostname as arg to `kube-config`

**Comment by lavvy** [comment]
I don't have a working cluster yet . I believe It should work.
Can you confirm

**Comment by lavvy** [comment]
Guys,  any confirmed test so far on this ?

**Comment by luxas** [comment]
No, I can't ping my master from a worker. Can't even the master from itself by hostname.
Is this very important to you? I guess some more services/daemons are required for this or otherwise it's just my router...

**Comment by lavvy** [comment]
Yeah,  i think this should be important cos,  it will ease the setup for
hybrid clusters

**Comment by luxas** [comment]
Feel free to try to install resolving software once you have your cluster up and running. 
But IP addresses aren't hard to remember either...

**Comment by luxas** [comment]
This hasn't anything to do with Kubernetes itself, it depends on your router/network setup locally.
If you can ping the node by name, you also may use the node name in `kube-config enable-worker [node-name]`, otherwise not.
