### ISSUE TITLE
Script downloads new image for every install.

### ISSUE THREAD

**Issue by GoldenBadger** [luxas/kubernetes-on-arm#56]
`sdcard/write.sh` downloads a new image every time you run it. If you are installing the image on a large number of SD cards in one go, `/etc/tmp` fills up quite rapidly with redundant copies of the image. It also adds a large amount of time to the installation process. Having it only download an image if one does not already exist would be a nice change.

**Comment by luxas** [comment]
Hello!
Sure, I can fix it. I came across the same thing while writing some SD cards last week, just haven't had time to do it, but now I can patch that.
Thanks for notifying me :)

**Comment by luxas** [comment]
Haven't tested it but should work: 4aa7cccc3ac5899c1ae65aac7b9995299ea4c241
Just remember that the `dev` branch is unstable, so test things on your own risk

**Comment by luxas** [comment]
I think this is fixed with `v0.6.5`. Reopen if not
