### ISSUE TITLE
/usr/bin/kube-config is not executable

### ISSUE THREAD

**Issue by nsteinmetz** [luxas/kubernetes-on-arm#6]
With 0.5.5 on Rasp V1, /usr/bin/kube-config is not executable

So it requires 

```
chmod +x /usr/bin/kube-config
```

before being able to run kube-config install.

**Comment by luxas** [comment]
I've checked it out and it seems all files in the git repo are non-executable. I have to update my git env

**Comment by luxas** [comment]
Fixed with [this commit](https://github.com/luxas/kubernetes-on-arm/commit/8eb17b6858b5d71f61088cdb778f5ec79309d851)
Closing this. It will be available in the next release or if you use `master`
