### ISSUE TITLE
At the end of kube-config, reboot is not properly managed

### ISSUE THREAD

**Issue by nsteinmetz** [luxas/kubernetes-on-arm#7]
You need to explicitely say/type yes for the reboot to work instead of just typing Enter as Y is set as default choice ;-)

**Comment by luxas** [comment]
Do you mean that Y should be default answer and only if n|N is answered, the program should not reboot?

**Comment by nsteinmetz** [comment]
Yes.

I think that Y can be the default answer as to make docker work you need the reboot.

**Comment by luxas** [comment]
Should be fixed with 13c6ead0c4d28302f992245feb58cfa34cc192a6
