### ISSUE TITLE
dashboard breaks when --apiserver-host is set to an https address

### ISSUE THREAD

**Issue by DorianGray** [luxas/kubernetes-on-arm#72]
Get https://10.0.0.1/api/v1/replicationcontrollers: x509: failed to load system roots and no roots provided

It looks like the docker image for the dashboard isn't provisioned with a system level cacert and go is getting mad that it can't find -any- certificates on the host.

**Comment by luxas** [comment]
This works, when there are Service Accounts, with #69 there are not, and that's the problem.

**Comment by DorianGray** [comment]
ah...got it.

**Comment by DorianGray** [comment]
It looks like I have service accounts working now, but the issue persists. The dashboard image seems to be missing a root cert.

**Comment by DorianGray** [comment]
nvm, I'm an idiot. It works fine.
